import { useEffect,useState } from "react";
import { useNavigate } from "react-router-dom";
import { Pencil,Trash2,Power,Eye,GripVertical } from "lucide-react";
import AdminModuleShell from "../../components/AdminModuleShell";
const KEY="ashSubcategories";
const seed=['Bangles', 'Necklaces', 'Earrings', 'Rings', 'Anklets'].map((name,i)=>({id:`subcategories-${i+1}`,name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),status:"Active",order:i+1,description:"ASH Jewellery catalogue record"}));
function load(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):seed}catch{return seed}}
export default function Subcategories(){const nav=useNavigate();const[items,setItems]=useState(load);const[search,setSearch]=useState("");const[status,setStatus]=useState("All");useEffect(()=>localStorage.setItem(KEY,JSON.stringify(items)),[items]);const filtered=items.filter(x=>(status==="All"||x.status===status)&&`${x.name} ${x.slug}`.toLowerCase().includes(search.toLowerCase()));const toggle=id=>setItems(items.map(x=>x.id===id?{...x,status:x.status==="Active"?"Inactive":"Active"}:x));const remove=id=>{if(confirm("Delete this record?"))setItems(items.filter(x=>x.id!==id))};return <AdminModuleShell title="Subcategories" description="Manage category-level groupings, ordering, status and SEO." actionLabel="Add Subcategory" onAction={()=>nav("/subcategories/new")} search={search} onSearch={setSearch} searchPlaceholder="Search subcategories..." filters={<select className="module-select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Inactive</option></select>}><div className="products-card module-card"><div className="products-card-header"><div><h2>Subcategories list</h2><p>{filtered.length} records</p></div></div><div className="products-table-wrapper"><table className="products-table module-table"><thead><tr><th>ORDER</th><th>NAME</th><th>SLUG</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><GripVertical size={14}/> {item.order}</td><td><div className="product-cell"><div className="module-record-icon">{item.name.slice(0,1)}</div><div><strong className="product-name">{item.name}</strong><span className="sku">{item.description}</span></div></div></td><td><span className="sku">/{item.slug}</span></td><td><span className={`status-badge ${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="module-actions"><button onClick={()=>alert(`${item.name}

Status: ${item.status}`)}><Eye size={15}/></button><button onClick={()=>nav(`/subcategories/${item.id}/edit`)}><Pencil size={15}/></button><button onClick={()=>toggle(item.id)}><Power size={15}/></button><button className="danger-icon" onClick={()=>remove(item.id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="products-empty"><h3>No subcategories found</h3><p>Try another search or create a new record.</p></div>}</div></AdminModuleShell>}
