/**
 * Centralized Role-Based Access Control (RBAC) Permission Matrix
 * Defines all system permissions and role mappings for ASH Jewellery
 */

export const PERMISSIONS = Object.freeze({
  // Users & Admins
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DISABLE: "USER_DISABLE",

  // Products
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Categories & Subcategories
  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  // Collections
  COLLECTION_VIEW: "COLLECTION_VIEW",
  COLLECTION_CREATE: "COLLECTION_CREATE",
  COLLECTION_UPDATE: "COLLECTION_UPDATE",
  COLLECTION_DELETE: "COLLECTION_DELETE",

  // Attributes
  ATTRIBUTE_VIEW: "ATTRIBUTE_VIEW",
  ATTRIBUTE_CREATE: "ATTRIBUTE_CREATE",
  ATTRIBUTE_UPDATE: "ATTRIBUTE_UPDATE",
  ATTRIBUTE_DELETE: "ATTRIBUTE_DELETE",

  // Tags
  TAG_VIEW: "TAG_VIEW",
  TAG_CREATE: "TAG_CREATE",
  TAG_UPDATE: "TAG_UPDATE",
  TAG_DELETE: "TAG_DELETE",

  // Media Library
  MEDIA_VIEW: "MEDIA_VIEW",
  MEDIA_CREATE: "MEDIA_CREATE",
  MEDIA_UPDATE: "MEDIA_UPDATE",
  MEDIA_DELETE: "MEDIA_DELETE",

  // Homepage CMS — Hero
  HERO_VIEW: "HERO_VIEW",
  HERO_UPDATE: "HERO_UPDATE",

  // Homepage CMS — Banners
  BANNER_VIEW: "BANNER_VIEW",
  BANNER_CREATE: "BANNER_CREATE",
  BANNER_UPDATE: "BANNER_UPDATE",
  BANNER_DELETE: "BANNER_DELETE",

  // Homepage CMS — Special Offers
  SPECIAL_OFFER_VIEW: "SPECIAL_OFFER_VIEW",
  SPECIAL_OFFER_CREATE: "SPECIAL_OFFER_CREATE",
  SPECIAL_OFFER_UPDATE: "SPECIAL_OFFER_UPDATE",
  SPECIAL_OFFER_DELETE: "SPECIAL_OFFER_DELETE",

  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Settings
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_UPDATE: "SETTINGS_UPDATE",
});

/**
 * Role to Permissions Mapping
 */
export const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    // Products
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    // Categories
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    // Collections
    PERMISSIONS.COLLECTION_VIEW,
    PERMISSIONS.COLLECTION_CREATE,
    PERMISSIONS.COLLECTION_UPDATE,
    PERMISSIONS.COLLECTION_DELETE,
    // Attributes
    PERMISSIONS.ATTRIBUTE_VIEW,
    PERMISSIONS.ATTRIBUTE_CREATE,
    PERMISSIONS.ATTRIBUTE_UPDATE,
    PERMISSIONS.ATTRIBUTE_DELETE,
    // Tags
    PERMISSIONS.TAG_VIEW,
    PERMISSIONS.TAG_CREATE,
    PERMISSIONS.TAG_UPDATE,
    PERMISSIONS.TAG_DELETE,
    // Media
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE,
    PERMISSIONS.MEDIA_DELETE,
    // Hero
    PERMISSIONS.HERO_VIEW,
    PERMISSIONS.HERO_UPDATE,
    // Banners
    PERMISSIONS.BANNER_VIEW,
    PERMISSIONS.BANNER_CREATE,
    PERMISSIONS.BANNER_UPDATE,
    PERMISSIONS.BANNER_DELETE,
    // Special Offers
    PERMISSIONS.SPECIAL_OFFER_VIEW,
    PERMISSIONS.SPECIAL_OFFER_CREATE,
    PERMISSIONS.SPECIAL_OFFER_UPDATE,
    PERMISSIONS.SPECIAL_OFFER_DELETE,
    // Settings view
    PERMISSIONS.SETTINGS_VIEW,
  ],

  STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,
    // Operational read & basic create/update (no destructive delete)
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.COLLECTION_VIEW,
    PERMISSIONS.ATTRIBUTE_VIEW,
    PERMISSIONS.TAG_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.HERO_VIEW,
    PERMISSIONS.BANNER_VIEW,
    PERMISSIONS.SPECIAL_OFFER_VIEW,
  ],
});

/**
 * Check if a role possesses a specific permission
 * @param {string} role - e.g. "SUPER_ADMIN", "ADMIN", "STAFF"
 * @param {string} permission - e.g. "PRODUCT_DELETE"
 * @returns {boolean}
 */
export function hasPermission(role, permission) {
  if (!role || !permission) return false;
  const permissions = ROLE_PERMISSIONS[role.toUpperCase()];
  if (!permissions) return false;
  return permissions.includes(permission);
}

export default {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
